clean_data.tool1_for_client$data |> select(any_of(extra_cols.tool1))
clean_data.tool1_for_client$Support_Respondents |> select(any_of(extra_cols.tool1))
clean_data.tool1_for_client$School_Operationality |> select(any_of(extra_cols.tool1))
clean_data.tool1_for_client$Shifts_Detail |> select(any_of(extra_cols.tool1))
clean_data.tool1_for_client$Headmasters |> select(any_of(extra_cols.tool1))
clean_data.tool1_for_client$Weekly_Class_Schedule |> select(any_of(extra_cols.tool1))
clean_data.tool1_for_client$Weekly_Class_Schedule_New |> select(any_of(extra_cols.tool1))
clean_data.tool1_for_client$Subjects_Detail |> select(any_of(extra_cols.tool1))
clean_data.tool1_for_client$Education_Quality |> select(any_of(extra_cols.tool1))
clean_data.tool1_for_client$Relevant_photos |> select(any_of(extra_cols.tool1))

clean_data.tool2_for_client$data |> select(any_of(extra_cols.tool2))
clean_data.tool2_for_client$Support_Respondents |> select(any_of(extra_cols.tool2))
clean_data.tool2_for_client$School_Operationality |> select(any_of(extra_cols.tool2))
clean_data.tool2_for_client$Shifts_Detail |> select(any_of(extra_cols.tool2))
clean_data.tool2_for_client$Headmasters |> select(any_of(extra_cols.tool2))
clean_data.tool2_for_client$Attendance_Sheet_Photos |> select(any_of(extra_cols.tool2))
clean_data.tool2_for_client$Public_Stationary_Kit_Group |> select(any_of(extra_cols.tool2))
clean_data.tool2_for_client$Teachers_Pack_Group |> select(any_of(extra_cols.tool2))
clean_data.tool2_for_client$Students_Pack_Group |> select(any_of(extra_cols.tool2))
clean_data.tool2_for_client$Relevant_photos |> select(any_of(extra_cols.tool2))

clean_data.tool3_for_client$data |> select(any_of(extra_cols.tool3))
clean_data.tool3_for_client$Support_Respondents |> select(any_of(extra_cols.tool3))
clean_data.tool3_for_client$Grade_Details |> select(any_of(extra_cols.tool3))
clean_data.tool3_for_client$Todays_Attendance_Detail |> select(any_of(extra_cols.tool3))
clean_data.tool3_for_client$Student_Headcount |> select(any_of(extra_cols.tool3))
clean_data.tool3_for_client$Tool3_Grades_Repeat |> select(any_of(extra_cols.tool3))
clean_data.tool3_for_client$Relevant_photos |> select(any_of(extra_cols.tool3))

clean_data.tool4_for_client$data |> select(any_of(extra_cols.tool4))
clean_data.tool4_for_client$Additional_Subjects |> select(any_of(extra_cols.tool4))
clean_data.tool4_for_client$Subjects_taught_by_this_teacher |> select(any_of(extra_cols.tool4))
clean_data.tool4_for_client$Subjects_Not_Being_Taught |> select(any_of(extra_cols.tool4))
clean_data.tool4_for_client$Relevant_photos |> select(any_of(extra_cols.tool4))

clean_data.tool5_for_client$data |> select(any_of(extra_cols.tool5))
clean_data.tool5_for_client$Under_Construction_Toilets |> select(any_of(extra_cols.tool5))
clean_data.tool5_for_client$Useable_Toilets |> select(any_of(extra_cols.tool5))
clean_data.tool5_for_client$Non_Useable_Toilets |> select(any_of(extra_cols.tool5))
clean_data.tool5_for_client$Relevant_photos |> select(any_of(extra_cols.tool5))

clean_data.tool6_for_client$data |> select(any_of(extra_cols.tool6))
clean_data.tool6_for_client$Subjects_Added |> select(any_of(extra_cols.tool6))
clean_data.tool6_for_client$Relevant_photos |> select(any_of(extra_cols.tool6))

clean_data.tool7_for_client$data |> select(any_of(extra_cols.tool7))
clean_data.tool7_for_client$Subjects_Added |> select(any_of(extra_cols.tool7))
clean_data.tool7_for_client$Relevant_photos |> select(any_of(extra_cols.tool7))
